### ISSUE TITLE
Possible to initialise with fixed image?

### ISSUE THREAD

**Issue by jtc42** [kovibalu/deepart#1]
Hi,

I've been looking around at various Python/caffe implementations of style transfer, and in most there is the option to use a fixed image as your init_img.

Is it possible to do something similar here? I realise it's likely not as simple as replacing the init_image in line 60 of gen_deepart, as this image is normalised to one and has no color information.

I'm basically clueless about this, but I thought it was worth asking anyway.

Thanks!

**Comment by paulu** [comment]
You can set init_img to a color image. If you look in deepart.py you will see that it ultimately calls net.preprocess_inputs on init_img. So, the color image will be transformed to the input that the model expects.

**Comment by jtc42** [comment]
Thanks! I've created a fork with options to use the content image as the initial image, with an easy option to switch between that and noise.
